kind: pipeline
name: default

steps:
  - name: deploy
    image: node
    environment:
      TOKEN:
        from_secret: exoframe_token
    commands:
      - npm install exoframe -g
      - exoframe endpoint https://exoframe.flower.codes
      - exoframe deploy -v -u -t $TOKEN

trigger:
  branch:
  - master
